[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GeoSuite"
authors = [{name = "AcuGIS", email = "hello@citedcorp.com"}]
dynamic = ["version", "description"]
